package prs.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import prs.domain.lineitem.LineItemRepository;
import prs.domain.lineitem.PurchaseRequestLineItem;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/LineItems") // This means URL's start with /demo (after Application path)
public class LineItemController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private LineItemRepository lineItemRepository;

//	@GetMapping(path="/Add") // Map ONLY POST Requests
//	public @ResponseBody Vendor addNewUser (@RequestParam Vendor vendor) {
//		// @ResponseBody means the returned String is the response, not a view name
//		// @RequestParam means it is a parameter from the GET or POST request
//        vendorRepository.save(vendor);
//        System.out.println("Vendor saved:  "+vendor);
//        return vendor;
//	}

	@GetMapping(path="/List") //currently products and vendors are linked
	public @ResponseBody Iterable<PurchaseRequestLineItem> getAllLineItems() {
		// This returns a JSON or XML with the users
		return lineItemRepository.findAll();
	}
	
    @GetMapping(path="/Get")
    public @ResponseBody PurchaseRequestLineItem getLineItem(@RequestParam int id) {
        PurchaseRequestLineItem li = lineItemRepository.findOne(id);
        return li;//Get?id= enter id # here
    }
    
    @GetMapping(path="/Delete")
    public @ResponseBody String deleteProduct(@RequestParam int id) {
        String msg = "";
        try {
            lineItemRepository.delete(id);
            msg = "Product " + id + " deleted";
        } catch (EmptyResultDataAccessException exc) {
            msg = "Product " + id + " doesn't exist...can't delete!";
        }
        return msg;
    }

}
