package prs.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import prs.domain.product.Product;
import prs.domain.product.ProductRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/Products") // This means URL's start with /demo (after Application path)
public class ProductController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private ProductRepository productRepository;

	@PostMapping(path="/Add") // Map ONLY POST Requests, hidden from URL
	public @ResponseBody Product addNewProduct (@RequestBody Product product) {
		//@ResponseBody means the returned Vendor is the response,not a view name
		//@RequestBody means it is a parameter from the POST request
		//vendor entity is going to transform JSON into instance of Vendor as vendor
		//if you do not request body, your values will be null
        productRepository.save(product);
        System.out.println("Product saved:  "+product);
        return product;
	}

	@GetMapping(path="/List") //currently products and vendors are linked
	public @ResponseBody Iterable<Product> getAllProducts() {
		// This returns a JSON or XML with the users
		return productRepository.findAll();
	}
	
    @GetMapping(path="/Get")
    public @ResponseBody Product getProduct(@RequestParam int id) {
        Product p = productRepository.findOne(id);
        return p;//Get?id= enter id # here
    }
    
    @GetMapping(path="/Delete")
    public @ResponseBody String deleteProduct(@RequestParam int id) {
        String msg = "";
        try {
            productRepository.delete(id);
            msg = "Product " + id + " deleted";
        } catch (EmptyResultDataAccessException exc) {
            msg = "Product " + id + " doesn't exist...can't delete!";
        }
        return msg;
    }

}
