package prs.web;

import java.sql.Timestamp;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import prs.domain.product.Product;
import prs.domain.purchase.PurchaseRepository;
import prs.domain.purchase.PurchaseRequest;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/PurchaseRequest") // This means URL's start with /demo (after Application path)
public class PurchaseController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private PurchaseRepository purchaseRepository;

	@PostMapping(path="/Add") // Map ONLY POST Requests, hidden from URL
	public @ResponseBody PurchaseRequest addNewPurchaseRequest (@RequestBody PurchaseRequest purchaseRequest) {
		//@ResponseBody means the returned Vendor is the response,not a view name
		//@RequestBody means it is a parameter from the POST request
		//vendor entity is going to transform JSON into instance of Vendor as vendor
		//if you do not request body, your values will be null
		Timestamp ts = new Timestamp(System.currentTimeMillis());
        purchaseRequest.setSubmittedDate(ts);
        purchaseRepository.save(purchaseRequest);
        System.out.println("Purchase request saved:  "+purchaseRequest);
        return purchaseRequest;
	}

	@GetMapping(path="/List") //currently products and vendors are linked
	public @ResponseBody Iterable<PurchaseRequest> getAllProducts() {
		// This returns a JSON or XML with the users
		return purchaseRepository.findAll();
	}
	
    @GetMapping(path="/Get")
    public @ResponseBody PurchaseRequest getProduct(@RequestParam int id) {
        PurchaseRequest pr = purchaseRepository.findOne(id);
        return pr;//Get?id= enter id # here
    }
    
    @GetMapping(path="/Delete")
    public @ResponseBody String deleteProduct(@RequestParam int id) {
        String msg = "";
        try {
            purchaseRepository.delete(id);
            msg = "PurchaseRequest " + id + " deleted";
        } catch (EmptyResultDataAccessException exc) {
            msg = "PurchaseRequest " + id + " doesn't exist...can't delete!";
        }
        return msg;
    }

}
