package prs.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import prs.domain.status.Status;
import prs.domain.status.StatusRepository;
import prs.domain.user.User;
import prs.domain.vendor.Vendor;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/Status") // This means URL's start with /demo (after Application path)
public class StatusController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private StatusRepository statusRepository;

	@PostMapping(path="/Add") // Map ONLY POST Requests, hidden from URL
	public @ResponseBody Status addNewStatus (@RequestBody Status status) {
		//@ResponseBody means the returned Vendor is the response,not a view name
		//@RequestBody means it is a parameter from the POST request
		//vendor entity is going to transform JSON into instance of Vendor as vendor
		//if you do not request body, your values will be null
        statusRepository.save(status);
        System.out.println("Status saved:  "+status);
        return status;
	}

	@GetMapping(path="/List") //currently products and vendors are linked
	public @ResponseBody Iterable<Status> getAllStatus() {
		// This returns a JSON or XML with the users
		return statusRepository.findAll();
	}
	
    @GetMapping(path="/Get")
    public @ResponseBody Status getStatus(@RequestParam int id) {
        Status s = statusRepository.findOne(id);
        return s;//Get?id= enter id # here
    }
    
    @GetMapping(path="/Delete")
    public @ResponseBody String deleteProduct(@RequestParam int id) {
        String msg = "";
        try {
            statusRepository.delete(id);
            msg = "Status " + id + " deleted";
        } catch (EmptyResultDataAccessException exc) {
            msg = "Status " + id + " doesn't exist...can't delete!";
        }
        return msg;
    }

}