package prs.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
//import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import prs.domain.product.Product;
import prs.domain.user.User;
import prs.domain.user.UserRepository;
import prs.domain.vendor.Vendor;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/Users") // This means URL's start with /demo (after Application path)
public class UserController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@PostMapping(path="/Add") // Map ONLY POST Requests, hidden from URL
	public @ResponseBody User addNewUser (@RequestBody User user) {
		//@ResponseBody means the returned Vendor is the response,not a view name
		//@RequestBody means it is a parameter from the POST request
		//vendor entity is going to transform JSON into instance of Vendor as vendor
		//if you do not request body, your values will be null
        userRepository.save(user);
        System.out.println("User saved:  "+user);
        return user;
	}

	@GetMapping(path="/List")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
	
    @GetMapping(path="/Get")
    public @ResponseBody User getUser(@RequestParam int id) {
        User u = userRepository.findOne(id);
        return u;//Get?id= enter id # here
    }
    
    @GetMapping(path="/Delete")
    public @ResponseBody String deleteUser(@RequestParam int id) {
        String msg = "";
        try {
            userRepository.delete(id);
            msg = "User " + id + " deleted";
        } catch (EmptyResultDataAccessException exc) {
            msg = "User " + id + " doesn't exist...can't delete!";
        }
        return msg;
    }

}

