package prs.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import prs.domain.lineitem.PurchaseRequestLineItem;
import prs.domain.user.User;
import prs.domain.vendor.Vendor;
import prs.domain.vendor.VendorRepository;
import prs.util.PRSMaintenanceReturn;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/Vendors") // This means URL's start with /demo (after Application path)
public class VendorController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private VendorRepository vendorRepository;

	@PostMapping(path="/Add") // Map ONLY POST Requests, hidden from URL
	public @ResponseBody PRSMaintenanceReturn addNewVendor (@RequestBody Vendor vendor) {
		//@ResponseBody means the returned Vendor is the response,not a view name
		//@RequestBody means it is a parameter from the POST request
		//translates json into a java object
		//vendor entity is going to transform JSON into instance of Vendor as vendor
		//if you do not request body, your values will be null
        vendorRepository.save(vendor);
        System.out.println("Vendor saved:  "+vendor);
        return PRSMaintenanceReturn.getMaintReturn(vendor);
	}

	@PostMapping(path="/Change") // Map ONLY POST Requests, hidden from URL
	public @ResponseBody PRSMaintenanceReturn changeVendor (@RequestBody Vendor vendor) {
		//@ResponseBody means the returned Vendor is the response,not a view name
		//@RequestBody means it is a parameter from the POST request
		//vendor entity is going to transform JSON into instance of Vendor as vendor
		//if you do not request body, your values will be null
		//pass the id in as well to change the log of the vendor
        vendorRepository.save(vendor);
        System.out.println("User saved:  "+vendor);
        return PRSMaintenanceReturn.getMaintReturn(vendor);
	}
	
	@GetMapping(path="/List")
	public @ResponseBody Iterable<Vendor> getAllVendors() {
		// This returns a JSON or XML with the users
		return vendorRepository.findAll();
	}
	
    @GetMapping(path="/Get")
    public @ResponseBody Vendor[] getVendor(@RequestParam int id) {
        Vendor v = vendorRepository.findOne(id);
        return getReturnArray(v);//Get?id= enter id # here
    }
    
    @GetMapping(path="/Delete") //change your delete  to match sean's
    public @ResponseBody PRSMaintenanceReturn deleteVendor(@RequestParam int id) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		Vendor vendor = vendorRepository.findOne(id);
		vendorRepository.delete(vendor);
		return PRSMaintenanceReturn.getMaintReturn(vendor);
    }
    
	private Vendor[] getReturnArray(Vendor v) {
		Vendor[] returnArray;
		if (v == null) {
			returnArray = new Vendor[0];
		} else {
			returnArray = new Vendor[1];
			returnArray[0] = v;
		}
		return returnArray;
	}

}
