package prs.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import prs.domain.vendor.Vendor;
import prs.domain.vendor.VendorRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/Vendors") // This means URL's start with /demo (after Application path)
public class VendorController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private VendorRepository vendorRepository;

	@PostMapping(path="/Add") // Map ONLY POST Requests, hidden from URL
	public @ResponseBody Vendor addNewVendor (@RequestBody Vendor vendor) {
		//@ResponseBody means the returned Vendor is the response,not a view name
		//@RequestBody means it is a parameter from the POST request
		//vendor entity is going to transform JSON into instance of Vendor as vendor
		//if you do not request body, your values will be null
        vendorRepository.save(vendor);
        System.out.println("Vendor saved:  "+vendor);
        return vendor;
	}

	@GetMapping(path="/List")
	public @ResponseBody Iterable<Vendor> getAllVendors() {
		// This returns a JSON or XML with the users
		return vendorRepository.findAll();
	}
	
    @GetMapping(path="/Get")
    public @ResponseBody Vendor getVendor(@RequestParam int id) {
        Vendor v = vendorRepository.findOne(id);
        return v;//Get?id= enter id # here
    }
    
    @GetMapping(path="/Delete")
    public @ResponseBody String deleteVendor(@RequestParam int id) {
        String msg = "";
        try {
            vendorRepository.delete(id);
            msg = "Vendor " + id + " deleted";
        } catch (EmptyResultDataAccessException exc) {
            msg = "Vendor " + id + " doesn't exist...can't delete!";
        }
        return msg;
    }

}
